version: "3.8"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test-shopper
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U root -d test-shopper']
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - test_shopper_db:/var/lib/postgresql/data
    ports:
      - '5433:5432'

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: 
      - .env
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src:/app/src

volumes:
  test_shopper_db:
